### ISSUE TITLE
Cannot specify size of DB volumes for Database Service

### ISSUE THREAD

**Issue by drauba** [terraform-providers/terraform-provider-oraclepaas#44]
Database Service instances automatically creates the following storage volumes:

1. instance/db_1/vm-1/boot
2. instance/db_1/vm-1/redo
3. instance/db_1/vm-1/fra
4. instance/db_1/vm-1/bits    
5. instance/db_1/vm-1/data   

the boot volume I can set with the "usable_storage" parameter in database_configuration, however the capacity for the 4 other db volumes cannot be modified. 

This is possible through the dbcs-cli https://docs.oracle.com/en/cloud/paas/database-dbaas-cloud/csdbi/oracle-dbcs-cli-create-data-file.html (see db_vols)

**Comment by scross01** [comment]
#48 (wip) will address this for increasing the size of the data backup (fra) volumes.

According to the [API docs](https://docs.oracle.com/en/cloud/paas/database-dbaas-cloud/csdbr/op-paas-service-dbcs-api-v1.1-instances-identitydomainid-serviceid-put.html) only `data` and `fra` resizing are supported.

**Comment by mbfrahry** [comment]
Hey @drauba. This will be fixed in the next release. As @scross01 pointed out, we can only update `data` and `fra` through the api and those attributes will be `data_storage_volume_size` and `backup_storage_volume_size` respectively.
