### ISSUE TITLE
oraclepaas cannot manage BYOL or not

### ISSUE THREAD

**Issue by tseoracle** [terraform-providers/terraform-provider-oraclepaas#50]
oraclepaas bring_your_own_license parameter no more work for both DBCS and JCS.
I was told
"It looks like the change to the default behavior in the JCS API that has broken the Terraform provider, we just had a similar issue with DBCS. The provider assumes that not setting the byol flag would imply cloud license, which is the old API behavior."
Here's the description of the problem.
---
We are now using terraform-provider-oraclepaas_v1.3.0_x4.
    
    According to the doc,
     
    https://www.terraform.io/docs/providers/oraclepaas/r/oraclepaas_java_service_instance.html
    it says,
    "bring_your_own_license - (Optional) Flag that specifies whether to 
    apply an existing on-premises license for Oracle WebLogic Server (true) 
    to the new Oracle Java Cloud Service instance you are provisioning. The 
    default value is false."
    
    This means
      if we not set "bring_your_own_license" or set it to "false", it would be,
         License: Cloud License
    But actually it's always
         License: BYOL
---

**Comment by mbfrahry** [comment]
Hey @tseoracle, this fix has just been released. Feel free to reopen this issue if you continue to have problems

**Comment by tseoracle** [comment]
Hello, Matthew.
Thank you for fixing BYOL stuff and
also updated #55 "service_instance cannot update timeouts".

#55 was closed and I don't know how to reopen it.
Your fixes were only in JCS instance.
We need it for DBCS instance, too.

Could you please take care of it?

Thanks,
  Takeshi
