### ISSUE TITLE
Creating MySQL in existing subnet fails

### ISSUE THREAD

**Issue by wneirynck** [terraform-providers/terraform-provider-oraclepaas#69]
When trying to create an MySQL instance in an existing subnet, this fails with a 400 error.

The cause is that because of an error in the Oracle REST documentation, the "subnet" property is put under the wrong map key.  It should be in the "serviceParameters" tag, not under "mysql".

Example:
This REST body does not work (but is as documented):
```
{
  "componentParameters": {
    "mysql": {
      "subnet": "some-subnet-ocid"
      ...
    }
}
...
```

It should be like this (and it works, I've tried it):

```
{
  ...
  "serviceParameters": {
    "subnet": "some-subnet-ocid",
    ...
  }
}
```

**Comment by mbfrahry** [comment]
Hey @wneirynck, thanks for opening this issue. I've found/fixed/released the issue in version 1.5.3 of the provider. Feel free to reopen this if you continue to have issues.
